name: scbasecount-py
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.13
  - scanpy=1.10
  - anndata=0.11
  - pandas=2.2
  - pyarrow=19.0
  - gcsfs=2025.2
  - google-cloud-storage=3.0
  - fsspec=2025.2
  - jupyter=1.1
  - jupyterlab=4.3
  - notebook=7.3
  - ipykernel=6.29
